import React, { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import {
  fetchEventTeams,
  createTeam,
  deleteTeam,
  fetchAutoGeneratedTeams,
} from "../../../../api/team";
import { fetchEventParticipants } from "../../../../api/participant";
import { fetchFormats } from "../../../../api/format";
import { extractErrorMessage } from "../../../../utils/errorHandler";
import type { CreateTeamPayload, ProposedTeam } from "../../../../types/api";

export const TeamsTab: React.FC<{ eventId: number }> = ({ eventId }) => {
  const queryClient = useQueryClient();
  const [showAddTeam, setShowAddTeam] = useState(false);
  const [showAutoGenerate, setShowAutoGenerate] = useState(false);
  const [newTeam, setNewTeam] = useState<CreateTeamPayload>({
    name: "",
    participant_ids: [],
    is_temporary: false,
  });
  const [selectedFormat, setSelectedFormat] = useState("");
  const [proposedTeams, setProposedTeams] = useState<ProposedTeam[]>([]);
  const [isSavingProposals, setIsSavingProposals] = useState(false);
  const [swapSelection, setSwapSelection] = useState<{
    teamIdx: number;
    speakerIdx: number;
  } | null>(null);

  const { data: teamsData, isLoading: teamsLoading } = useQuery({
    queryKey: ["teams", eventId],
    queryFn: () => fetchEventTeams(eventId),
  });
  const { data: participantData } = useQuery({
    queryKey: ["participants", eventId, "all"],
    queryFn: () => fetchEventParticipants(eventId, 1, 1000),
    enabled: showAddTeam,
  });
  const { data: formats } = useQuery({
    queryKey: ["formats"],
    queryFn: fetchFormats,
  });

  const addTeamMutation = useMutation({
    mutationFn: (payload: CreateTeamPayload) => createTeam(eventId, payload),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["teams", eventId] });
      setNewTeam({ name: "", participant_ids: [], is_temporary: false });
      setShowAddTeam(false);
    },
    onError: (error) =>
      alert(extractErrorMessage(error, "Failed to create team.")),
  });

  const removeTeamMutation = useMutation({
    mutationFn: (teamId: number) => deleteTeam(eventId, teamId),
    onSuccess: () =>
      queryClient.invalidateQueries({ queryKey: ["teams", eventId] }),
    onError: (error) =>
      alert(extractErrorMessage(error, "Failed to dissolve team.")),
  });

  const generateMutation = useMutation({
    mutationFn: (formatId: number) =>
      fetchAutoGeneratedTeams(eventId, formatId),
    onSuccess: (data) => setProposedTeams(data),
    onError: (error) =>
      alert(extractErrorMessage(error, "Failed to generate teams.")),
  });

  const handleAddTeamSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    addTeamMutation.mutate(newTeam);
  };

  const handleParticipantSelect = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const selectedOptions = Array.from(e.target.selectedOptions, (option) =>
      parseInt(option.value, 10),
    );
    setNewTeam({ ...newTeam, participant_ids: selectedOptions });
  };

  const handleGenerateRequest = (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedFormat) return;
    generateMutation.mutate(parseInt(selectedFormat, 10));
  };

  const handleRenameProposal = (teamIdx: number, newName: string) => {
    const updatedProposals = [...proposedTeams];
    updatedProposals[teamIdx].name = newName;
    setProposedTeams(updatedProposals);
  };

  const handleSpeakerClick = (teamIdx: number, speakerIdx: number) => {
    if (!swapSelection) {
      setSwapSelection({ teamIdx, speakerIdx });
    } else {
      const updatedProposals = [...proposedTeams];
      const teamA = updatedProposals[swapSelection.teamIdx];
      const teamB = updatedProposals[teamIdx];
      const speakerA = teamA.participants[swapSelection.speakerIdx];
      const speakerB = teamB.participants[speakerIdx];

      teamA.participants[swapSelection.speakerIdx] = speakerB;
      teamB.participants[speakerIdx] = speakerA;
      teamA.participant_ids[swapSelection.speakerIdx] = speakerB.id;
      teamB.participant_ids[speakerIdx] = speakerA.id;

      setProposedTeams(updatedProposals);
      setSwapSelection(null);
    }
  };

  const handleSaveProposals = async () => {
    setIsSavingProposals(true);
    try {
      await Promise.all(
        proposedTeams.map((team) =>
          createTeam(eventId, {
            name: team.name,
            participant_ids: team.participant_ids,
            is_temporary: true,
          }),
        ),
      );
      queryClient.invalidateQueries({ queryKey: ["teams", eventId] });
      setProposedTeams([]);
      setShowAutoGenerate(false);
    } catch (error) {
      alert(extractErrorMessage(error, "Error saving teams."));
    } finally {
      setIsSavingProposals(false);
    }
  };

  return (
    <div>
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          marginBottom: "1rem",
        }}
      >
        <h2>Teams</h2>
        <div style={{ display: "flex", gap: "1rem" }}>
          <button
            onClick={() => {
              setShowAddTeam(!showAddTeam);
              setShowAutoGenerate(false);
            }}
            className="btn btn-success"
          >
            {showAddTeam ? "Close Manual Entry" : "+ Manual Team"}
          </button>
          <button
            onClick={() => {
              setShowAutoGenerate(!showAutoGenerate);
              setShowAddTeam(false);
            }}
            className="btn btn-info"
          >
            {showAutoGenerate ? "Cancel Auto-Gen" : "🪄 Auto-Generate"}
          </button>
        </div>
      </div>

      {showAddTeam && (
        <form
          onSubmit={handleAddTeamSubmit}
          className="form-grid panel"
          style={{ alignItems: "start" }}
        >
          <div className="form-group" style={{ marginBottom: 0 }}>
            <label className="form-label">Team Name *</label>
            <input
              type="text"
              required
              value={newTeam.name}
              onChange={(e) => setNewTeam({ ...newTeam, name: e.target.value })}
              className="form-input"
            />
            <label
              className="form-group"
              style={{
                display: "flex",
                alignItems: "center",
                gap: "0.5rem",
                marginTop: "1rem",
              }}
            >
              <input
                type="checkbox"
                checked={newTeam.is_temporary}
                onChange={(e) =>
                  setNewTeam({ ...newTeam, is_temporary: e.target.checked })
                }
              />
              Is Temporary? (Can be dissolved later)
            </label>
          </div>
          <div className="form-group" style={{ marginBottom: 0 }}>
            <label className="form-label">
              Select Speakers (Hold Ctrl/Cmd to select multiple) *
            </label>
            <select
              multiple
              required
              value={newTeam.participant_ids.map(String)}
              onChange={handleParticipantSelect}
              className="form-input"
              style={{ minHeight: "120px" }}
            >
              {participantData?.participants
                .filter((p) => p.role === "speaker" && !p.is_eliminated)
                .map((p) => (
                  <option key={p.id} value={p.id}>
                    {p.display_name} (ID: {p.id})
                  </option>
                ))}
            </select>
          </div>
          <button
            type="submit"
            disabled={
              addTeamMutation.isPending || newTeam.participant_ids.length === 0
            }
            className="btn btn-primary"
            style={{ gridColumn: "span 2" }}
          >
            {addTeamMutation.isPending ? "Creating..." : "Create Team"}
          </button>
        </form>
      )}

      {showAutoGenerate && (
        <div className="panel">
          <h3 style={{ marginTop: 0 }}>Auto-Generate Temporary Teams</h3>
          <p className="text-muted">
            Select a format. The system will pair all unassigned speakers into
            temporary teams.
          </p>
          <form
            onSubmit={handleGenerateRequest}
            style={{
              display: "flex",
              gap: "1rem",
              alignItems: "end",
              marginBottom: "1.5rem",
            }}
          >
            <div className="form-group" style={{ flex: 1, marginBottom: 0 }}>
              <label className="form-label">Select Format</label>
              <select
                value={selectedFormat}
                onChange={(e) => setSelectedFormat(e.target.value)}
                required
                className="form-input"
              >
                <option value="" disabled>
                  -- Select a Format --
                </option>
                {formats?.map((f) => (
                  <option key={f.id} value={f.id}>
                    {f.name} ({f.speakers_per_team} speakers/team)
                  </option>
                ))}
              </select>
            </div>
            <button
              type="submit"
              disabled={generateMutation.isPending || !selectedFormat}
              className="btn btn-info"
            >
              {generateMutation.isPending
                ? "Calculating..."
                : "Generate Proposals"}
            </button>
          </form>

          {proposedTeams.length > 0 && (
            <div
              style={{
                background: "var(--bg-light)",
                padding: "1.5rem",
                borderRadius: "8px",
                border: "1px dashed var(--info)",
              }}
            >
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "center",
                }}
              >
                <h3 style={{ marginTop: 0, color: "var(--info)" }}>
                  Proposed Pairings ({proposedTeams.length} teams)
                </h3>
                {swapSelection && (
                  <span
                    style={{
                      fontSize: "0.9rem",
                      color: "var(--warning)",
                      fontWeight: "bold",
                    }}
                  >
                    Select another speaker to swap...
                  </span>
                )}
              </div>
              <ul
                style={{
                  display: "grid",
                  gridTemplateColumns: "1fr 1fr",
                  gap: "1rem",
                  padding: 0,
                  listStyle: "none",
                }}
              >
                {proposedTeams.map((team, tIdx) => (
                  <li
                    key={tIdx}
                    style={{
                      padding: "1rem",
                      border: "1px solid var(--border)",
                      borderRadius: "4px",
                      background: "var(--bg)",
                    }}
                  >
                    <input
                      type="text"
                      value={team.name}
                      onChange={(e) =>
                        handleRenameProposal(tIdx, e.target.value)
                      }
                      style={{
                        fontWeight: "bold",
                        border: "none",
                        borderBottom: "1px dashed var(--border)",
                        background: "transparent",
                        width: "100%",
                        fontSize: "1rem",
                        marginBottom: "0.5rem",
                        padding: "0.2rem",
                      }}
                    />
                    <ul
                      style={{
                        margin: 0,
                        padding: 0,
                        listStyle: "none",
                        display: "flex",
                        flexDirection: "column",
                        gap: "0.5rem",
                      }}
                    >
                      {team.participants.map((sp, sIdx) => {
                        const isSelected =
                          swapSelection?.teamIdx === tIdx &&
                          swapSelection?.speakerIdx === sIdx;
                        return (
                          <li
                            key={sp.id}
                            onClick={() => handleSpeakerClick(tIdx, sIdx)}
                            style={{
                              padding: "0.5rem",
                              background: isSelected
                                ? "var(--warning)"
                                : "var(--bg-light)",
                              color: isSelected
                                ? "var(--bg-light)"
                                : "var(--secondary)",
                              border: `1px solid ${isSelected ? "var(--warning)" : "var(--border)"}`,
                              borderRadius: "4px",
                              cursor: "pointer",
                              fontSize: "0.9rem",
                              transition: "all 0.2s",
                            }}
                          >
                            {sp.display_name}
                          </li>
                        );
                      })}
                    </ul>
                  </li>
                ))}
              </ul>
              <div
                style={{ marginTop: "1.5rem", display: "flex", gap: "1rem" }}
              >
                <button
                  onClick={handleSaveProposals}
                  disabled={isSavingProposals}
                  className="btn btn-success"
                >
                  {isSavingProposals ? "Saving..." : "Confirm & Save Teams"}
                </button>
                <button
                  onClick={() => {
                    setProposedTeams([]);
                    setSwapSelection(null);
                  }}
                  disabled={isSavingProposals}
                  className="btn btn-outline-danger"
                >
                  Discard Proposals
                </button>
              </div>
            </div>
          )}
        </div>
      )}

      {teamsLoading ? (
        <p>Loading teams...</p>
      ) : (
        <table className="data-table">
          <thead>
            <tr>
              <th>ID</th>
              <th>Team Name</th>
              <th>Type</th>
              <th>Speakers</th>
              <th>Status</th>
              <th style={{ textAlign: "right" }}>Actions</th>
            </tr>
          </thead>
          <tbody>
            {teamsData?.map((team) => (
              <tr key={team.id}>
                <td>#{team.id}</td>
                <td style={{ fontWeight: "bold" }}>{team.name}</td>
                <td>
                  <span
                    className={`badge ${team.is_temporary ? "badge-warning" : "badge-info"}`}
                  >
                    {team.is_temporary ? "Temporary" : "Permanent"}
                  </span>
                </td>
                <td>
                  <ul
                    style={{
                      margin: 0,
                      paddingLeft: "1.2rem",
                      color: "var(--secondary)",
                    }}
                  >
                    {team.speakers.map((sp) => (
                      <li key={sp.participant_id}>{sp.name}</li>
                    ))}
                  </ul>
                </td>
                <td>{team.is_eliminated ? "Eliminated" : "Active"}</td>
                <td style={{ textAlign: "right" }}>
                  <button
                    onClick={() => {
                      if (window.confirm("Dissolve this team?"))
                        removeTeamMutation.mutate(team.id);
                    }}
                    className="btn btn-outline-danger btn-sm"
                  >
                    Dissolve
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  );
};
