import { apiClient } from "../../../api/axios";
import type {
  EventTeam,
  CreateTeamPayload,
  ProposedTeam,
} from "../../../types/api";

export const fetchEventTeams = async (
  eventId: number,
  is_temporary?: boolean,
): Promise<EventTeam[]> => {
  const query =
    is_temporary !== undefined ? `?is_temporary=${is_temporary}` : "";
  const response = await apiClient.get(`/events/${eventId}/teams${query}`);
  return response.data.data;
};
export const createTeam = async (
  eventId: number,
  payload: CreateTeamPayload,
): Promise<EventTeam> => {
  const response = await apiClient.post(`/events/${eventId}/teams`, payload);
  return response.data.data;
};
export const deleteTeam = async (
  eventId: number,
  teamId: number,
): Promise<void> => {
  await apiClient.delete(`/events/${eventId}/teams/${teamId}`);
};
export const fetchAutoGeneratedTeams = async (
  eventId: number,
  formatId: number,
): Promise<ProposedTeam[]> => {
  const response = await apiClient.get(
    `/events/${eventId}/teams/auto-generate?format_id=${formatId}`,
  );
  return response.data.data.proposed_teams;
};
